supported_currencies = {
    "AFN": "Afghan Afghani", "AED": "United Arab Emirates Dirham", "ALL": "Albanian Lek", "AMD": "Armenian Dram", 
    "ANG": "Netherlands Antillean Guilder", "AOA": "Angolan Kwanza", "ARS": "Argentine Peso", "AUD": "Australian Dollar", 
    "AWG": "Aruban Florin", "AZN": "Azerbaijani Manat", "BAM": "Bosnia-Herzegovina Convertible Mark", "BBD": "Barbadian Dollar", 
    "BDT": "Bangladeshi Taka", "BGN": "Bulgarian Lev", "BHD": "Bahraini Dinar", "BIF": "Burundian Franc", 
    "BMD": "Bermudian Dollar", "BND": "Brunei Dollar", "BOB": "Bolivian Boliviano", "BRL": "Brazilian Real", 
    "BSD": "Bahamian Dollar", "BTC": "Bitcoin", "BTN": "Bhutanese Ngultrum", "BWP": "Botswana Pula", 
    "BYN": "Belarusian Ruble", "BZD": "Belize Dollar", "CAD": "Canadian Dollar", "CDF": "Congolese Franc", 
    "CHF": "Swiss Franc", "CLF": "Chilean Unit of Account (UF)", "CLP": "Chilean Peso", "CNH": "Chinese Yuan (Offshore)", 
    "CNY": "Chinese Yuan", "COP": "Colombian Peso", "CRC": "Costa Rican Colón", "CUC": "Cuban Convertible Peso", 
    "CUP": "Cuban Peso", "CVE": "Cape Verdean Escudo", "CZK": "Czech Koruna", "DJF": "Djiboutian Franc", 
    "DKK": "Danish Krone", "DOP": "Dominican Peso", "DZD": "Algerian Dinar", "EGP": "Egyptian Pound", 
    "ERN": "Eritrean Nakfa", "ETB": "Ethiopian Birr", "EUR": "Euro", "FJD": "Fijian Dollar", "FKP": "Falkland Islands Pound", 
    "GBP": "British Pound", "GEL": "Georgian Lari", "GGP": "Guernsey Pound", "GHS": "Ghanaian Cedi", 
    "GIP": "Gibraltar Pound", "GMD": "Gambian Dalasi", "GNF": "Guinean Franc", "GTQ": "Guatemalan Quetzal", 
    "GYD": "Guyanese Dollar", "HKD": "Hong Kong Dollar", "HNL": "Honduran Lempira", "HRK": "Croatian Kuna", 
    "HTG": "Haitian Gourde", "HUF": "Hungarian Forint", "IDR": "Indonesian Rupiah", "ILS": "Israeli New Shekel", 
    "IMP": "Isle of Man Pound", "INR": "Indian Rupee", "IQD": "Iraqi Dinar", "IRR": "Iranian Rial", "ISK": "Icelandic Krona", 
    "JEP": "Jersey Pound", "JMD": "Jamaican Dollar", "JOD": "Jordanian Dinar", "JPY": "Japanese Yen", 
    "KES": "Kenyan Shilling", "KGS": "Kyrgyzstani Som", "KHR": "Cambodian Riel", "KMF": "Comorian Franc", 
    "KPW": "North Korean Won", "KRW": "South Korean Won", "KWD": "Kuwaiti Dinar", "KYD": "Cayman Islands Dollar", 
    "KZT": "Kazakhstani Tenge", "LAK": "Lao Kip", "LBP": "Lebanese Pound", "LKR": "Sri Lankan Rupee", 
    "LRD": "Liberian Dollar", "LSL": "Lesotho Loti", "LYD": "Libyan Dinar", "MAD": "Moroccan Dirham", 
    "MDL": "Moldovan Leu", "MGA": "Malagasy Ariary", "MKD": "Macedonian Denar", "MMK": "Myanmar Kyat", 
    "MNT": "Mongolian Tugrik", "MOP": "Macanese Pataca", "MRU": "Mauritanian Ouguiya", "MUR": "Mauritian Rupee", 
    "MVR": "Maldivian Rufiyaa", "MWK": "Malawian Kwacha", "MXN": "Mexican Peso", "MYR": "Malaysian Ringgit", 
    "MZN": "Mozambican Metical", "NAD": "Namibian Dollar", "NGN": "Nigerian Naira", "NIO": "Nicaraguan Córdoba", 
    "NOK": "Norwegian Krone", "NPR": "Nepalese Rupee", "NZD": "New Zealand Dollar", "OMR": "Omani Rial", 
    "PAB": "Panamanian Balboa", "PEN": "Peruvian Sol", "PGK": "Papua New Guinean Kina", "PHP": "Philippine Peso", 
    "PKR": "Pakistani Rupee", "PLN": "Polish Zloty", "PYG": "Paraguayan Guarani", "QAR": "Qatari Riyal", 
    "RON": "Romanian Leu", "RSD": "Serbian Dinar", "RUB": "Russian Ruble", "RWF": "Rwandan Franc", 
    "SAR": "Saudi Riyal", "SBD": "Solomon Islands Dollar", "SCR": "Seychellois Rupee", "SDG": "Sudanese Pound", 
    "SEK": "Swedish Krona", "SGD": "Singapore Dollar", "SHP": "Saint Helena Pound", "SLL": "Sierra Leonean Leone", 
    "SOS": "Somali Shilling", "SRD": "Surinamese Dollar", "SSP": "South Sudanese Pound", "STD": "São Tomé and Príncipe Dobra (pre-2018)", 
    "STN": "São Tomé and Príncipe Dobra", "SVC": "Salvadoran Colón", "SYP": "Syrian Pound", "SZL": "Swazi Lilangeni", 
    "THB": "Thai Baht", "TJS": "Tajikistani Somoni", "TMT": "Turkmenistani Manat", "TND": "Tunisian Dinar", 
    "TOP": "Tongan Paʻanga", "TRY": "Turkish Lira", "TTD": "Trinidad and Tobago Dollar", "TWD": "New Taiwan Dollar", 
    "TZS": "Tanzanian Shilling", "UAH": "Ukrainian Hryvnia", "UGX": "Ugandan Shilling", "USD": "United States Dollar", 
    "UYU": "Uruguayan Peso", "UZS": "Uzbekistani Som", "VES": "Venezuelan Bolívar Soberano", "VND": "Vietnamese Dong", 
    "VUV": "Vanuatu Vatu", "WST": "Samoan Tala", "XAF": "Central African CFA Franc", "XAG": "Silver Ounce", 
    "XAU": "Gold Ounce", "XCD": "East Caribbean Dollar", "XDR": "Special Drawing Rights", "XOF": "West African CFA Franc", 
    "XPD": "Palladium Ounce", "XPF": "CFP Franc", "XPT": "Platinum Ounce", "YER": "Yemeni Rial", 
    "ZAR": "South African Rand", "ZMW": "Zambian Kwacha", "ZWL": "Zimbabwean Dollar"
}

currency_symbols = {
    "AFN": ("Afs", True), "AED": ("AED", True), "ALL": ("Lek", False), "AMD": ("Dram", False),
    "AOA": ("Kz", False), "ARS": ("$", True), "AUD": ("$", True), "AWG": ("ƒ", True), "AZN": ("₼", True),
    "BAM": ("KM", False), "BBD": ("$", True), "BDT": ("Tk", False), "BGN": ("лв", False), "BHD": ("BHD", True),
    "BIF": ("Fr", False), "BMD": ("$", True), "BND": ("$", True), "BOB": ("Bs", False), "BRL": ("R$", True),
    "BSD": ("$", True), "BTC": ("₿", True), "BTN": ("Nu", False), "BWP": ("P", False), "BYN": ("Br", False),
    "BZD": ("$", True), "CAD": ("$", True), "CDF": ("Fr", False), "CHF": ("Fr", False), "CLF": ("UF", False),
    "CLP": ("$", True), "CNH": ("¥", True), "CNY": ("¥", True), "COP": ("$", True), "CRC": ("₡", True),
    "CUC": ("₱", True), "CUP": ("₱", True), "CVE": ("$", True), "CZK": ("Kč", False), "DJF": ("Fr", False),
    "DKK": ("kr", False), "DOP": ("$", True), "DZD": ("DZD", False), "EGP": ("EGP", False), "ERN": ("Nfk", False),
    "ETB": ("Birr", False), "EUR": ("€", True), "FJD": ("$", True), "FKP": ("£", False), "GBP": ("£", False),
    "GEL": ("₾", True), "GGP": ("£", False), "GHS": ("₵", False), "GIP": ("£", False), "GMD": ("D", False),
    "GNF": ("Fr", False), "GTQ": ("Q", False), "GYD": ("$", True), "HKD": ("$", True), "HNL": ("L", False),
    "HRK": ("kn", False), "HTG": ("G", False), "HUF": ("Ft", False), "IDR": ("Rp", True), "ILS": ("₪", True),
    "IMP": ("£", False), "INR": ("₹", True), "IQD": ("IQD", False), "IRR": ("IRR", False), "ISK": ("kr", False),
    "JEP": ("£", False), "JMD": ("$", True), "JOD": ("JD", False), "JPY": ("¥", True), "KES": ("KSh", False),
    "KGS": ("с", False), "KHR": ("៛", False), "KMF": ("Fr", False), "KPW": ("₩", False), "KRW": ("₩", False),
    "KWD": ("KWD", True), "KYD": ("$", True), "KZT": ("₸", False), "LAK": ("₭", False), "LBP": ("L.L", False),
    "LKR": ("Rs", False), "LRD": ("$", True), "LSL": ("L", False), "LYD": ("LYD", True), "MAD": ("DH", False),
    "MDL": ("Leu", False), "MGA": ("Ar", False), "MKD": ("ден", False), "MMK": ("Ks", False), "MNT": ("₮", False),
    "MOP": ("MOP", False), "MRU": ("UM", False), "MUR": ("₨", False), "MVR": ("MVR", False), "MWK": ("MK", False),
    "MXN": ("$", True), "MYR": ("RM", False), "MZN": ("MT", False), "NAD": ("$", True), "NGN": ("₦", True),
    "NIO": ("C$", True), "NOK": ("kr", False), "NPR": ("₨", False), "NZD": ("$", True), "OMR": ("Rial", True),
    "PAB": ("B/.", False), "PEN": ("S/.", False), "PGK": ("K", False), "PHP": ("₱", False), "PKR": ("Rs", False),
    "PLN": ("zł", False), "PYG": ("₲", False), "QAR": ("QR", False), "RON": ("lei", False), "RSD": ("din", False),
    "RUB": ("₽", False), "RWF": ("Fr", False), "SAR": ("SAR", True), "SBD": ("$", True), "SCR": ("₨", False),
    "SDG": ("SDG", False), "SEK": ("kr", False), "SGD": ("$", True), "SHP": ("£", False), "SLL": ("Le", False),
    "SOS": ("S", False), "SRD": ("$", True), "SSP": ("SSP", False), "STD": ("Db", False), "STN": ("STN", False),
    "SVC": ("₡", False), "SYP": ("SYP", False), "SZL": ("SZL", False), "THB": ("฿", False), "TJS": ("SM", False),
    "TMT": ("T", False), "TND": ("DT", False), "TOP": ("T$", True), "TRY": ("₺", True), "TTD": ("TT$", True),
    "TWD": ("NT$", True), "TZS": ("Sh", False), "UAH": ("₴", True), "UGX": ("Sh", False), "USD": ("$", True),
    "UYU": ("$", True), "UZS": ("so'm", False), "VES": ("Bs", False), "VND": ("₫", False), "VUV": ("Vt", False),
    "WST": ("T", False), "XAF": ("Fr", False), "XAG": ("oz", False), "XAU": ("oz", False), "XCD": ("EC$", False),
    "XDR": ("XDR", False), "XOF": ("Fr", False), "XPD": ("oz", False), "XPF": ("Fr", False), "XPT": ("oz", False),
    "YER": ("YR", False), "ZAR": ("R", False), "ZMW": ("ZK", False), "ZWL": ("Z$", True)
}
